root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./main ./cmd/main.go"
bin = "main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor" "bleve_index"]
exclude_file = []
exclude_regex = ["_test\\.go"]
follow_symlink = true
log = "air.log"
full_bin = "PRODUCTION=false ./main"

poll = false
